<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Flyaround\FlyschemaSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Airport
 *
 * Structure class for relation flyschema.airport.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Airport extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('flyschema.airport')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('name', 'varchar')
            ->addField('icao', 'varchar')
            ->addField('coordinates', 'point')
            ->addField('address', 'varchar')
            ->addField('city', 'varchar')
            ->addField('country', 'varchar')
            ;
    }
}
