<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Flyaround\FlyschemaSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Flight
 *
 * Structure class for relation flyschema.flight.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Flight extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('flyschema.flight')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('created_at', 'timestamp')
            ->addField('updated_at', 'timestamp')
            ->addField('takeoff_time', 'timestamp')
            ->addField('landing_time', 'timestamp')
            ->addField('flight_duration', 'tsrange')
            ->addField('depart_city', 'int4')
            ->addField('arrival_city', 'int4')
            ->addField('free_seats', 'int4')
            ->addField('seat_price', 'numeric')
            ->addField('pilot', 'int4')
            ->addField('was_done', 'bool')
            ;
    }
}
