<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Flyaround\FlyschemaSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Review
 *
 * Structure class for relation flyschema.review.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Review extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('flyschema.review')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('created_at', 'timestamp')
            ->addField('updated_at', 'timestamp')
            ->addField('flight', 'int4')
            ->addField('reviewed_pilot', 'int4')
            ->addField('comment', 'text')
            ;
    }
}
