<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Flyaround\FlyschemaSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * User
 *
 * Structure class for relation flyschema.user.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class User extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('flyschema.user')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('created_at', 'timestamp')
            ->addField('updated_at', 'timestamp')
            ->addField('username', 'varchar')
            ->addField('lastname', 'varchar')
            ->addField('firstname', 'varchar')
            ->addField('password', 'varchar')
            ->addField('email', 'varchar')
            ->addField('role', 'varchar')
            ->addField('is_certified_pilot', 'bool')
            ;
    }
}
